# conda env create -f environment.yml
name: lume-genesis-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - lume-base
#  - genesis2=*=mpi_mpich*
  - genesis4=4.6.4=mpi_openmpi* # Pinned because of a bug in 4.6.5
# Developer
  - ffmpeg
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python

