# conda env create -f environment.yml
name: lume-genesis-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - eval-type-backport
  - lume-base
  - genesis2=*=mpi_openmpi*
  - genesis4 >=4.6.7=mpi_openmpi*
  - h5py=*=mpi_openmpi*
  - jinja2
  - lark
  - numpy
  - prettytable
  - psutil
  - pydantic >2
  - pydantic-settings
  # Developer
  - ffmpeg
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - jupyterlab-lsp
  - python-lsp-server
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-jupyter
  - mkdocs-material
  - mkdocstrings-python
  - ruff
  - typing-extensions
  - pip
  - pip:
      # TODO: remove prior to merging
      - git+https://github.com/ken-lauer/openPMD-beamphysics.git/@fix_genesis4_4.6.7
