# conda env create -f environment.yml
name: lume-genesis-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - eval-type-backport
  - lume-base
#  - genesis2=*=mpi_mpich*
  - genesis4 >=4.6.6=mpi_openmpi*
  - jinja2
  - lark
  - prettytable
  - pydantic >2
# Developer
  - ffmpeg
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - ruff
  - typing-extensions
